create table public.users
(
    id        bigint generated by default as identity
        constraint users_pk
            primary key,
    name      varchar,
    password      varchar,
    email     varchar,
    image     varchar,
    createdat timestamp,
    updatedat timestamp
);

