CREATE TABLE public.users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT users_pk
            PRIMARY KEY,
    name       VARCHAR,
    password   VARCHAR,
    email      VARCHAR,
    image      VARCHAR,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

