pinta:
  home:
    ssh:
      username: ${SSH_USERNAME}
      password: ${SSH_PASSWORD}
      host: ${SSH_HOST}
      port: ${SSH_PORT}
    jwt:
      key: ${JWT_KEY}
      expiration: ${JWT_EXPIRATION:3600000}
spring:
  application:
    name: homeserver
  datasource:
#    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:user}
    url: ${DB_URL:jdbc:h2:mem:testdb}
    password: ${DB_PASSWORD:password}
  liquibase:
    enabled: ${LB_ENABLED:true}
server:
  port: '8080'